pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.9' }
      }
      steps {
        sh 'mvn --version'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:22.0' }
      }
      steps {
        sh 'node --version'
      }
    }

    stage('Database') {
      agent {
        docker { image 'mysql:8.0' }  // You can specify 8.0.36 if needed
      }
      environment {
        MYSQL_ROOT_PASSWORD = 'rootpass'
        MYSQL_DATABASE = 'testdb'
      }
      steps {
        script {
          echo 'Starting MySQL and checking status...'
          sh '''
            echo "Waiting for MySQL to start..."
            for i in {1..10}; do
              if mysqladmin ping -h "127.0.0.1" --silent; then
                echo "MySQL is ready"
                break
              fi
              echo "Waiting..."
              sleep 3
            done
          '''
        }
      }
    }
  }

  post {
    always {
      echo 'Pipeline finished.'
    }
  }
}
